### PR TITLE
Refactor/ moved parsing of parameters into superclass

### PR DESCRIPTION
**Pull request by Der-Penz**
I moved the parsing of the parameter into the `api.ts` superclass to avoid having to call the parseOptions function all the time.

## Changes Made:

- Moved parsing of options into the `get` function of the superclass `api.ts`.
- Updated all endpoints classes to pass the options into the `get` function instead of parsing it.

### CODE REVIEW

**Comment by blakejoy** [comment]
Good refactor. Looks like merge conflicts after adding linting/formatting

**Comment by Der-Penz** [comment]
I hope i didn't break anything during the merge, maybe take a look on it.

**Review by blakejoy — APPROVED** [review]
LGTM

**Comment by blakejoy** [comment]
> LGTM

Bump the minor version

**Pull request merged**
