### PR TITLE
feat - add linting and prettier

### PR DESCRIPTION
**Pull request by blakejoy**
Fix/Add different linting rules and added prettier for formatting.

### CODE REVIEW

**Comment by Hoidi** [comment]
Seems to be working 👍 

However, I get lineending diffs on all files when running the fotmat command. Is this because I'm on windows and it does some weird stuff or did you forget to run it one last time?

**Comment by blakejoy** [comment]
> Seems to be working 👍
> 
> However, I get lineending diffs on all files when running the fotmat command. Is this because I'm on windows and it does some weird stuff or did you forget to run it one last time?

Hmmm yeah I’m on Mac I think it’s checking for LF. I believe Windows uses CR/CR+LF. Let me see if I can make it more exclusive.

**Comment by blakejoy** [comment]
Does lint:fix resolve the issue or does the ide complain still ?

**Comment by Hoidi** [comment]
It's git that complains, not the ide. And running lint:fix doesn't fix it. 

Should the .prettierrc still contain `"endOfLine": "lf"` if you want to rurn off linebreak rules?

**Comment by blakejoy** [comment]
> It's git that complains, not the ide. And running lint:fix doesn't fix it.
> 
> Should the .prettierrc still contain `"endOfLine": "lf"` if you want to rurn off linebreak rules?

Ahh so this is coming from git.. is it an actual error or a warning?

**Comment by Hoidi** [comment]
It's a warning
`warning: in the working copy of 'src/endpoints/account.ts', LF will be replaced by CRLF the next time Git touches it`

**Comment by Der-Penz** [comment]
Is adding husky in consideration?

**Comment by blakejoy** [comment]
> Is adding husky in consideration?

It's added.

**Pull request merged**
