### PR TITLE
Add people endpoint

### PR DESCRIPTION
**Pull request by Der-Penz**
# People endpoint!

I added support for the [people endpoints](https://www.themoviedb.org/settings/api). All HTTP Get requests for the people TMDB endpoint are supported.

## Additions

- New types for people

- People endpoint added to the TMDB class

- All GET endpoints with /person: details, changes, movie_credits, tv_credits, combined_credits, external_ids, images, tagged_images, translations, latest, popular

### CODE REVIEW

**Comment by blakejoy** [comment]
I think since this introduces some changes to the types it may break some of the current implementations. I would be down to bump this to a major version to reduce that.

**Comment by Der-Penz** [comment]
I am trying to add the currently missing endpoints in the near future. The old ones should be tested if they are still up to date.

**Comment by blakejoy** [comment]
> I am trying to add the currently missing endpoints in the near future. The old ones should be tested if they are still up to date.

Yup understand that but the new addition on `PaginatedResult` type would cause a breaking change for anyone pulling in the latest minor/patch version. If you want to, you can add the people endpoint and in a subsequent request update the types.

**Comment by Der-Penz** [comment]
Ok I am going to rewrite the endpoint to use the basic people endpoint and make a seperate pull request with the PaginatedResult

**Comment by blakejoy** [comment]
> Ok I am going to rewrite the endpoint to use the basic people endpoint and make a seperate pull request with the PaginatedResult



> Ok I am going to rewrite the endpoint to use the basic people endpoint and make a seperate pull request with the PaginatedResult

Sounds like a plan 😂

**Pull request closed without merging**
